monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: info
            handler: nested
            excluded_http_codes: [404, 405]
        nested:
            type: stream
            path: "php://stderr"
            level: info
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine"]

        critical_mail:
            type:         fingers_crossed
            # 500 errors are logged at the critical level
            action_level: critical
            # to also log 400 level errors (but not 404's):
            # action_level: error
            # excluded_404s:
            #     - ^/
            handler:      deduplicated
        deduplicated:
            type:    deduplication
            handler: mailer
            formatter:  monolog.formatter.html
        mailer:
            type: service
            id: symfony_mailer_monolog
